require 'options'
require 'plugins'
require 'nvim-tree-config'
require 'autopairs-config'
require 'telescope-config'
require 'toggleterm-config'
-- require 'null-ls-config'
require 'format-config'
require 'treesitter-config'
require 'lspsaga-config'
require 'comment-config'
require 'theme'
require 'lsp'
require 'colorizer-config'
